on:
  push:
    branches:
      - main

name: 🚀 Deploy production
concurrency: push_main

permissions: write-all

env:
  CI: true

jobs:
  build-format-lint-test:
    name: 🚀 Build, format, lint and test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install & cache node dependencies
        uses: ./.github/actions/install-node-deps
      - name: '💄 Check format'
        run: pnpm format-check
      - name: '🧪 Test linter'
        run: pnpm nx affected --targets=test-linter,test-type,test-circular
      - name: '🧪 Run unit tests'
        run: pnpm nx run-many --target=test-unit
      - name: Install LCOV
        run: |
          sudo apt-get update
          sudo apt-get install lcov
      - name: '🔃 Merge lcov files'
        run: ./scripts/merge-lcov.sh
